import os
from pymatgen.core.composition import Composition
from pymatgen.core.periodic_table import Element
from pymatgen.analysis.phase_diagram import PhaseDiagram, PDPlotter, PDEntry
import matplotlib.pyplot as plt
import plotly.express as px
import pandas as pd
import numpy as np
import joblib
import json
from CBFV.composition import generate_features
from sklearn.preprocessing import normalize, StandardScaler
from smact.screening import smact_validity


def filter_valid_compounds(compounds):
    valid_compounds = []
    for comp in compounds:
        if smact_validity(Composition(comp)):
            valid_compounds.append(comp)
    return valid_compounds

# Example usage



def load_model(model_path):
    return None

def check_for_simplifcation(previous_data, ijk):
    for data in previous_data:

        if data[0] != 0:
            k = ijk[0]/data[0]
        elif data[1] != 0:
            k = ijk[1]/data[1]
        elif data[2] != 0:
            k = ijk[2]/data[2]
        
        if all([data[0]*k == ijk[0], data[1]*k == ijk[1], data[2]*k == ijk[2]]):
            return True
    return False
#load model 

gen_data = False
if gen_data:
    n_max = 15
    elements = ["Ag","Al","Au","B","Ba","Bi","Be","Ca","Cd","Co","Cr","Cs","Cu","Fe","Ga","Ge","K","Hf","Hg","In","Ir","La","Li","Mg","Mn","Mo","Na","Nb","Ni","Os","Pb","Pd","Pt","Rb","Re","Rh","Ru","Sb","Sc","Sr","Sn","Ta","Tc","Ti","Tl","W","Y","Zr","Zn"]

    for element in elements:
        coeff_list = []
        formulas = []
        for i in range(n_max + 1):
            for j in range(n_max + 1):
                for k in range(n_max + 1):
                    #skip the case where all the values are 0
                    if i == 0 and j == 0 and k == 0:
                        continue
                    else:
                        if i + j + k <= 20:
                            if not check_for_simplifcation(coeff_list, [i, j, k]):
                                formula = f"{element}{i}P{j}S{k}"
                                formulas.append(formula)
                                coeff_list.append([i, j, k])
        #filter out the invalid compounds
        formulas = filter_valid_compounds(formulas)

        target = [0 for i in range(len(formulas))]
        #make a dataframe from the formulas and target
        df = pd.DataFrame({"formula": formulas, "target": target})
        print(df['formula'])
        scaler = StandardScaler()
        
        #we need to make select for only the features that were used in the model
        #the features are stored in the json file as strings the name of the features, so we need to convert them to integers
        #we need the list of feaures generated by the generate_features function
        #for every in feature in features we need to find the index in the feature_heads list
        # we can then use this index to select the correct columns from the X_test dataframe
        y_pred = model.predict(X_test)
        y_pred = y_pred.tolist()
        ternary_data = pd.DataFrame({"formula": formulas, "target": y_pred})
        ternary_data.to_csv(f"plotting/data/ternary_FE/ternary_data_{element}.csv", index=False)

PATH = os.getcwd()
total_formulas = []
total_unstable_formulas = []
total_formation_energies = []
total_unstable_hulls = []
total_unstable_formation_energies = []
elements = ["Ag","Al","Au","B","Ba","Bi","Be","Ca","Cd","Co","Cr","Cs","Cu","Fe","Ga","Ge","K","Hf","Hg","In","Ir","La","Li","Mg","Mn","Mo","Na","Nb","Ni","Os","Pb","Pd","Pt","Rb","Re","Rh","Ru","Sb","Sc","Sr","Sn","Ta","Tc","Ti","Tl","W","Y","Zr","Zn"]
for element in elements:
    Fl = []
    #import ternary data as csv
    ternary_data = pd.read_csv(PATH+f'/plotting/data/ternary_FE/ternary_data_{element}.csv')
    #we want to get the bandgap fro each mateial from the bandgap data files
    ternary_BG_data = pd.read_csv(PATH+f"/plotting/data/ternary_BG/{element}_ternary_data.csv")
    #we want to get the bandgap for each material from the bandgap data files
    bandgaps = {}
    for i in range(len(ternary_data)):
        formula = ternary_data.iloc[i]['formula']
        BG = ternary_BG_data[ternary_BG_data['formula'] == formula]['target'].values[0]
        formula = Composition(formula).reduced_formula
        bandgaps[formula] = BG

    #we want to convert the data into a list of PDEntry objects where the first entry is the composition and the second entry is the energy
    el_list = ternary_data.to_numpy()
    print(el_list)
    for i in el_list:
        print(Composition(i[0]))
        Fl.append(PDEntry(i[0], i[1]*Composition(i[0]).num_atoms))

    PD = PhaseDiagram(Fl)
    #I want to save the stable compunds witht heir formation energy to a csv this includes elements above the hull by less than 0.1 eV
    stable_entries = PD.stable_entries
    formation_energies = [PD.get_form_energy_per_atom(e) for e in stable_entries]
    #also want unstable entires to be saved
    unstable_entries = PD.unstable_entries
    unstable_energies = [PD.get_form_energy_per_atom(e) for e in unstable_entries]
    unstable_hull_energies = [PD.get_e_above_hull(e) for e in unstable_entries]
    formulas_unstable = [e.composition.reduced_formula for e in unstable_entries]


    formulas = [e.composition.reduced_formula for e in stable_entries]
    print("formulas", formulas)
    print("formation energies", formation_energies)
    print("length of formulas", len(formulas))
    print("length of formation energies", len(formation_energies))
    #save a csv with the stable compounds and their formation energies
    total_formulas += formulas
    total_unstable_formulas += formulas_unstable
    total_formation_energies += formation_energies
    total_unstable_formation_energies += unstable_energies
    total_unstable_hulls += unstable_hull_energies
    stables = pd.DataFrame({"formula": formulas, "formation_energy": formation_energies})
    
    #sort the stable compounds by formation energy
    stables = stables.sort_values(by="formation_energy")
    #we save in a "data" folder
    if not os.path.exists(PATH+f'/plotting/data/'):
        os.makedirs(PATH+f'/plotting/data/')
    stables.to_csv(PATH+f'/plotting/data//stable_compounds_{element}.csv', index=False)






    print(PD)
    #dont show the text for every point

    plot_kwargs = {
    "markerfacecolor": "orange",
    "markersize": 12,
    "linewidth": 4,}

    # Create plotter instance with custom styles
    plotter = PDPlotter(PD, backend="matplotlib", bandgap_data=bandgaps,bandgap_mode=True, **plot_kwargs)
    energy_colormap = plt.get_cmap('Oranges_r')  # You can choose any colormap you prefer
    energy_colormap.reversed()

    # Call the get_plot function with the desired colormap
    #kwargs = {'show_colorbar':True}
    ax = plotter.get_plot(

        label_unstable=False,  # If you want to label unstable points  # If you want to display a colorbar
        label_stable=True,
        energy_colormap=energy_colormap,
        ordering=[element, "P", "S"],)
    # Additional customizations
    plt.title(f"Phase Diagram of {element}", fontsize=35)
    # I want to save the plot in the plotting/figures/ternary_plots_FE folder
    plt.savefig(PATH+f'/plotting/figures/ternary_plots_FE/BG_ternary_plot_{element}.png')
    #I also wanto to save the plot in a folder corresponding to the column of the periodic table the element is in
    column = Element(element).group
    if not os.path.exists(PATH+f'/plotting/figures/ternary_plots_FE/{column}'):
        os.makedirs(PATH+f'/plotting/figures/ternary_plots_FE/{column}')
    plt.savefig(PATH+f'/plotting/figures/ternary_plots_FE/{column}/BG_ternary_plot_{element}.png')
    #we also want to make 3d plots
    plotter = PDPlotter(PD, ternary_style='3d')
    #same thing here with groups
    
    if not os.path.exists(PATH+f'/plotting/figures/ternary_plots_FE/{column}/html'):
        os.makedirs(PATH+f'/plotting/figures/ternary_plots_FE/{column}/html')
    plotter.get_plot(ordering=["P","S", element]).write_html(PATH+f'/plotting/figures/ternary_plots_FE/{column}/html/ternary_plot_{element}.html')
total_stables = pd.DataFrame({"formula": total_formulas, "formation_energy": total_formation_energies})
#sort the dataframe by formation energy
total_stables = total_stables.sort_values(by="formation_energy")
total_stables.to_csv(PATH+f'/plotting/data/total_stable_compounds.csv', index=False)
#now weant to make a bigger list of all the unstable compounds up to 0.2ev off the hull
total_unstable = pd.DataFrame({"formula": total_unstable_formulas, "formation_energy":total_unstable_formation_energies , "energy above hull": total_unstable_hulls})
#we remove what is higher than 0.2 eV above the hull
total_unstable = total_unstable[total_unstable['energy above hull'] <= 0.2]
#sort
total_unstable = total_unstable.sort_values(by="formation_energy")
total_unstable.to_csv(PATH+f'/plotting/data/total_unstable_compounds.csv', index=False)
