_target_: src.fett.model.lightning_module.FettLightningModule
model:
  _target_: src.fett.model.set_based_model.SetBasedBandgapModel
  embedding_dim: 172
  fidelity_dim: 20
  hidden_dim: 288
  num_blocks: 5
  num_fidelities: 6
  num_elements: 118
  num_heads: 16
  dropout: 0.17912079167770537
  pooling_type: weighted
